# Generated by Django 4.2.2 on 2023-06-26 08:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_vacancy_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='view',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
