# Generated by Django 4.2.2 on 2023-06-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=900, verbose_name='ФИО')),
                ('specialization', models.CharField(max_length=64, verbose_name='Специализация')),
                ('an_expect_salary', models.IntegerField(verbose_name='ожидаемая зарплата')),
                ('is_searching', models.BooleanField(default=True, verbose_name='Ожидаемая зарплата')),
            ],
        ),
    ]
