# Generated by Django 4.2.2 on 2023-06-26 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_worker_user_alter_worker_name_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='ФИО')),
                ('specialization', models.CharField(max_length=64, verbose_name='Специализация')),
                ('an_expect_salary', models.IntegerField(verbose_name='ожидаемая зарплата')),
                ('experience', models.TextField(verbose_name='Опыт работы')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.worker')),
            ],
        ),
    ]
