# Generated by Django 4.2.2 on 2023-07-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_company_created_at_resume_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created_at',
        ),
    ]
