# Generated by Django 4.2.2 on 2023-07-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_remove_company_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='workers',
            field=models.ManyToManyField(related_name='company', to='worker.worker'),
        ),
    ]
